mwan3 bug

diff --git a/net/mwan3/files/etc/hotplug.d/iface/15-mwan3 b/net/mwan3/files/etc/hotplug.d/iface/15-mwan3
--- a/net/mwan3/files/etc/hotplug.d/iface/15-mwan3
+++ b/net/mwan3/files/etc/hotplug.d/iface/15-mwan3
@@ -6,73 +6,70 @@ mwan3_get_iface_id()
 	[ "$1" == "$INTERFACE" ] && iface_id=$iface_count
 }
 
-mwan3_set_general_iptables()
+mwan3_get_route_args()
 {
-	if ! $IPT -S mwan3_ifaces &> /dev/null; then
-		$IPT -N mwan3_ifaces
-	fi
-
-	if ! $IPT -S mwan3_rules &> /dev/null; then
-		$IPT -N mwan3_rules
-	fi
-
-	if ! $IPT -S mwan3_connected &> /dev/null; then
-		$IPT -N mwan3_connected
-	fi
-
-	if ! $IPT -S mwan3_hook &> /dev/null; then
-		$IPT -N mwan3_hook
-		$IPT -A mwan3_hook -j CONNMARK --restore-mark --nfmask 0xff00 --ctmask 0xff00
-		$IPT -A mwan3_hook -m mark --mark 0x0/0xff00 -j mwan3_ifaces
-		$IPT -A mwan3_hook -m mark --mark 0x0/0xff00 -j mwan3_connected
-		$IPT -A mwan3_hook -m mark --mark 0x0/0xff00 -j mwan3_rules
-		$IPT -A mwan3_hook -j CONNMARK --save-mark --nfmask 0xff00 --ctmask 0xff00
-		$IPT -A mwan3_hook -m mark ! --mark 0xff00/0xff00 -j mwan3_connected
-	fi
-
-	if ! $IPT -S mwan3_output_hook &> /dev/null; then
-		$IPT -N mwan3_output_hook
-	fi
-
-	if ! $IPT -S PREROUTING | grep mwan3_hook &> /dev/null; then
-		$IPT -A PREROUTING -j mwan3_hook
-	fi
-
-	if ! $IPT -S OUTPUT | grep mwan3_hook &> /dev/null; then
-		$IPT -A OUTPUT -j mwan3_hook
-	fi
-
-	if ! $IPT -S OUTPUT | grep mwan3_output_hook &> /dev/null; then
-		$IPT -A OUTPUT -j mwan3_output_hook
-	fi
-
-	$IPT -F mwan3_rules
+	route_args=$(ip -4 route list dev $DEVICE default | head -1 | sed '/.*via \([^ ]*\) .*$/!d;s//\1/;q' | egrep '[0-9]{1,3}(\.[0-9]{1,3}){3}')
+	[ -n "$route_args" ] && route_args="via $route_args"
+	route_args="nexthop $route_args dev $DEVICE"
 }
 
-mwan3_set_general_rules()
+mwan3_set_general_iptables()
 {
-	if [ -z "$($IP rule list | awk '$1 == "2253:"')" ]; then
-		$IP rule add pref 2253 fwmark 0xfd00/0xff00 blackhole
+	if ! iptables -S mwan3_ifaces -t mangle &> /dev/null; then
+		iptables -N mwan3_ifaces -t mangle
 	fi
 
-	if [ -z "$($IP rule list | awk '$1 == "2254:"')" ]; then
-		$IP rule add pref 2254 fwmark 0xfe00/0xff00 unreachable
+	if ! iptables -S mwan3_rules -t mangle &> /dev/null; then
+		iptables -N mwan3_rules -t mangle
 	fi
+
+	if ! iptables -S mwan3_connected -t mangle &> /dev/null; then
+		iptables -N mwan3_connected -t mangle
+	fi
+
+	if ! iptables -S mwan3_hook -t mangle &> /dev/null; then
+		iptables -N mwan3_hook -t mangle
+		iptables -A mwan3_hook -t mangle -j CONNMARK --restore-mark --nfmask 0xff00 --ctmask 0xff00
+		iptables -A mwan3_hook -t mangle -m mark --mark 0x0/0xff00 -j mwan3_ifaces
+		iptables -A mwan3_hook -t mangle -m mark --mark 0x0/0xff00 -j mwan3_connected
+		iptables -A mwan3_hook -t mangle -m mark --mark 0x0/0xff00 -j mwan3_rules
+		iptables -A mwan3_hook -t mangle -j CONNMARK --save-mark --nfmask 0xff00 --ctmask 0xff00
+	fi
+
+	if ! iptables -S mwan3_track_hook -t mangle &> /dev/null; then
+		iptables -N mwan3_track_hook -t mangle
+	fi
+
+	if ! iptables -S PREROUTING -t mangle | grep mwan3_hook &> /dev/null; then
+		iptables -A PREROUTING -t mangle -j mwan3_hook
+	fi
+
+	if ! iptables -S OUTPUT -t mangle | grep mwan3_hook &> /dev/null; then
+		iptables -A OUTPUT -t mangle -j mwan3_hook
+	fi
+
+	if ! iptables -S OUTPUT -t mangle | grep mwan3_track_hook &> /dev/null; then
+		iptables -A OUTPUT -t mangle -j mwan3_track_hook
+	fi
+
+	iptables -F mwan3_rules -t mangle
 }
 
 mwan3_set_connected_iptables()
 {
 	local connected_networks
 
-	if $IPT -S mwan3_connected &> /dev/null; then
-		$IPT -F mwan3_connected
+	if iptables -S mwan3_connected -t mangle &> /dev/null; then
+		iptables -F mwan3_connected -t mangle
 
-		for connected_networks in $($IP route | awk '{print $1}' | egrep '[0-9]{1,3}(\.[0-9]{1,3}){3}'); do
-			$IPT -A mwan3_connected -d $connected_networks -j MARK --set-xmark 0xff00/0xff00
+		for connected_networks in $(ip -4 route | awk '{print $1}' | egrep '[0-9]{1,3}(\.[0-9]{1,3}){3}'); do
+			iptables -A mwan3_connected -t mangle -d $connected_networks -m mark --mark 0x0/0xff00 -j MARK --set-xmark 0xff00/0xff00
 		done
 
-		$IPT -I mwan3_connected -d 224.0.0.0/3 -j MARK --set-xmark 0xff00/0xff00
-		$IPT -I mwan3_connected -d 127.0.0.0/8 -j MARK --set-xmark 0xff00/0xff00
+		iptables -I mwan3_connected -t mangle -d 224.0.0.0/3 -m mark --mark 0x0/0xff00 -j MARK --set-xmark 0xff00/0xff00
+		iptables -I mwan3_connected -t mangle -d 127.0.0.0/8 -m mark --mark 0x0/0xff00 -j MARK --set-xmark 0xff00/0xff00
+	else
+		return 0
 	fi
 }
 
@@ -80,51 +77,56 @@ mwan3_set_iface_iptables()
 {
 	local local_net local_nets
 
-	if ! $IPT -S mwan3_iface_$INTERFACE &> /dev/null; then
-		$IPT -N mwan3_iface_$INTERFACE
+	local_net=$(ip -4 route list dev $DEVICE scope link | awk '{print $1}' | egrep '[0-9]{1,3}(\.[0-9]{1,3}){3}')
+
+	if ! iptables -S mwan3_iface_$INTERFACE -t mangle &> /dev/null; then
+		iptables -N mwan3_iface_$INTERFACE -t mangle
 	fi
 
-	$IPT -F mwan3_iface_$INTERFACE
-	$IPT -D mwan3_ifaces -m mark --mark 0x0/0xff00 -j mwan3_iface_$INTERFACE &> /dev/null
+	iptables -F mwan3_iface_$INTERFACE -t mangle
+	iptables -D mwan3_ifaces -t mangle -i $DEVICE -m mark --mark 0x0/0xff00 -j mwan3_iface_$INTERFACE &> /dev/null
 
 	if [ $ACTION == "ifup" ]; then
-		local_nets=$($IP route list dev $DEVICE scope link | awk '{print $1}' | egrep '[0-9]{1,3}(\.[0-9]{1,3}){3}')
-
-		if [ -n "$local_nets" ]; then
-			for local_net in $local_nets ; do
+		if [ -n "$local_net" ]; then
+			for local_nets in $local_net ; do
 				if [ $ACTION == "ifup" ]; then
-					$IPT -I mwan3_iface_$INTERFACE -i $DEVICE -s $local_net -m mark --mark 0x0/0xff00 -m comment --comment "default" -j MARK --set-xmark 0xff00/0xff00
+					iptables -I mwan3_iface_$INTERFACE -t mangle -s $local_net -m mark --mark 0x0/0xff00 -m comment --comment "$INTERFACE" -j MARK --set-xmark 0xff00/0xff00
 				fi
 			done
 		fi
 
-		$IPT -A mwan3_iface_$INTERFACE -i $DEVICE -m mark --mark 0x0/0xff00 -m comment --comment "$INTERFACE" -j MARK --set-xmark $(($iface_id*256))/0xff00
-		$IPT -A mwan3_ifaces -m mark --mark 0x0/0xff00 -j mwan3_iface_$INTERFACE
+		iptables -A mwan3_iface_$INTERFACE -t mangle -m mark --mark 0x0/0xff00 -m comment --comment "$INTERFACE" -j MARK --set-xmark $(($iface_id*256))/0xff00
+		iptables -A mwan3_ifaces -t mangle -i $DEVICE -m mark --mark 0x0/0xff00 -j mwan3_iface_$INTERFACE
 	fi
 
 	if [ $ACTION == "ifdown" ]; then
-		$IPT -X mwan3_iface_$INTERFACE
+		iptables -X mwan3_iface_$INTERFACE -t mangle
 	fi
 }
 
 mwan3_set_iface_route()
 {
-	$IP route flush table $iface_id
-	[ $ACTION == "ifup" ] && $IP route add table $iface_id default $route_args
+	ip -4 route flush table $iface_id
+	[ $ACTION == "ifup" ] && ip -4 route add table $iface_id default $route_args
 }
 
 mwan3_set_iface_rules()
 {
-	while [ -n "$($IP rule list | awk '$1 == "'$(($iface_id+1000)):'"')" ]; do
-		$IP rule del pref $(($iface_id+1000))
+	while [ -n "$(ip -4 rule list | awk '$1 == "'$(($iface_id+1000)):'"')" ]; do
+		ip -4 rule del pref $(($iface_id+1000))
 	done
 
-	while [ -n "$($IP rule list | awk '$1 == "'$(($iface_id+2000)):'"')" ]; do
-		$IP rule del pref $(($iface_id+2000))
+	while [ -n "$(ip -4 rule list | awk '$1 == "'$(($iface_id+2000)):'"')" ]; do
+		ip -4 rule del pref $(($iface_id+2000))
 	done
 
-	[ $ACTION == "ifup" ] && $IP rule add pref $(($iface_id+1000)) iif $DEVICE lookup main
-	[ $ACTION == "ifup" ] && $IP rule add pref $(($iface_id+2000)) fwmark $(($iface_id*256))/0xff00 lookup $iface_id
+	while [ -n "$(ip -4 rule list | awk '$1 == "2254:"')" ]; do
+		ip -4 rule del pref 2254
+	done
+
+	[ $ACTION == "ifup" ] && ip -4 rule add pref $(($iface_id+1000)) iif $DEVICE lookup main
+	[ $ACTION == "ifup" ] && ip -4 rule add pref $(($iface_id+2000)) fwmark $(($iface_id*256))/0xff00 lookup $iface_id
+        ip rule add pref 2254 fwmark 0xfe00/0xff00 unreachable                                   
 }
 
 mwan3_track()
@@ -137,11 +139,6 @@ mwan3_track()
 	}
 	config_list_foreach $INTERFACE track_ip mwan3_list_track_ips
 
-	if [ -e /var/run/mwan3track-$INTERFACE.pid ] ; then
-		kill $(cat /var/run/mwan3track-$INTERFACE.pid) &> /dev/null
-		rm /var/run/mwan3track-$INTERFACE.pid &> /dev/null
-	fi
-
 	if [ -n "$track_ips" ]; then
 		config_get reliability $INTERFACE reliability 1
 		config_get count $INTERFACE count 1
@@ -150,28 +147,27 @@ mwan3_track()
 		config_get down $INTERFACE down 5
 		config_get up $INTERFACE up 5
 
-		if ! $IPT -S mwan3_track_$INTERFACE &> /dev/null; then
-			$IPT -N mwan3_track_$INTERFACE
-			$IPT -A mwan3_output_hook -p icmp -m icmp --icmp-type 8 -m length --length 32 -j mwan3_track_$INTERFACE
+		if ! iptables -S mwan3_track_$INTERFACE -t mangle &> /dev/null; then
+			iptables -N mwan3_track_$INTERFACE -t mangle
+			iptables -A mwan3_track_hook -t mangle -j mwan3_track_$INTERFACE
 		fi
 
-		$IPT -F mwan3_track_$INTERFACE
+		iptables -F mwan3_track_$INTERFACE -t mangle
 
 		for track_ip in $track_ips; do
-			$IPT -A mwan3_track_$INTERFACE -d $track_ip -j MARK --set-xmark 0xff00/0xff00
+			iptables -A mwan3_track_$INTERFACE -t mangle -p icmp -m icmp --icmp-type 8 -d $track_ip -o $DEVICE -j MARK --set-xmark 0xff00/0xff00
 		done
 
 		[ -x /usr/sbin/mwan3track ] && /usr/sbin/mwan3track $INTERFACE $DEVICE $reliability $count $timeout $interval $down $up $track_ips &
 	else
-		$IPT -D mwan3_output_hook -p icmp -m icmp --icmp-type 8 -m length --length 32 -j mwan3_track_$INTERFACE &> /dev/null
-		$IPT -F mwan3_track_$INTERFACE &> /dev/null
-		$IPT -X mwan3_track_$INTERFACE &> /dev/null
+		iptables -D mwan3_track_hook -t mangle -j mwan3_track_$INTERFACE &> /dev/null
+		iptables -X mwan3_track_$INTERFACE -t mangle &> /dev/null
 	fi
 }
 
 mwan3_set_policy()
 {
-	local iface_count iface_id INTERFACE metric probability weight
+	local iface_count iface_id metric probability weight
 
 	config_get INTERFACE $1 interface
 	config_get metric $1 metric 1
@@ -183,12 +179,12 @@ mwan3_set_policy()
 
 	[ -n "$iface_id" ] || return 0
 
-	if $IPT -S mwan3_iface_$INTERFACE &> /dev/null; then
+	if iptables -S mwan3_iface_$INTERFACE -t mangle &> /dev/null; then
 		if [ "$metric" -lt "$lowest_metric" ]; then
 
 			total_weight=$weight
-			$IPT -F mwan3_policy_$policy
-			$IPT -A mwan3_policy_$policy -m mark --mark 0x0/0xff00 -m comment --comment "$INTERFACE $weight $weight" -j MARK --set-xmark $(($iface_id*256))/0xff00
+			iptables -F mwan3_policy_$policy -t mangle
+			iptables -A mwan3_policy_$policy -t mangle -m mark --mark 0x0/0xff00 -m comment --comment "$INTERFACE $weight $weight" -j MARK --set-xmark $(($iface_id*256))/0xff00
 
 			lowest_metric=$metric
 
@@ -209,45 +205,34 @@ mwan3_set_policy()
 
 			probability="-m statistic --mode random --probability $probability"
 			
-			$IPT -I mwan3_policy_$policy -m mark --mark 0x0/0xff00 $probability -m comment --comment "$INTERFACE $weight $total_weight" -j MARK --set-xmark $(($iface_id*256))/0xff00
+			iptables -I mwan3_policy_$policy -t mangle -m mark --mark 0x0/0xff00 $probability -m comment --comment "$INTERFACE $weight $total_weight" -j MARK --set-xmark $(($iface_id*256))/0xff00
 		fi
 	fi
 }
 
 mwan3_set_policies_iptables()
 {
-	local last_resort lowest_metric policy total_weight
+	local lowest_metric policy total_weight
 
 	policy=$1
 
-	config_get last_resort $1 last_resort unreachable
-
 	if [ "$policy" != $(echo "$policy" | cut -c1-15) ]; then
-		$LOG warn "Policy $policy exceeds max of 15 chars. Not setting policy" && return 0
+		logger -t mwan3 -p warn "Policy $policy exceeds max of 15 chars. Not setting policy" && return 0
 	fi
 
-	if ! $IPT -S mwan3_policy_$policy &> /dev/null; then
-		$IPT -N mwan3_policy_$policy
+	if ! iptables -S mwan3_policy_$policy -t mangle &> /dev/null; then
+		iptables -N mwan3_policy_$policy -t mangle
 	fi
 
-	$IPT -F mwan3_policy_$policy
-
-	case "$last_resort" in
-		blackhole)
-			$IPT -A mwan3_policy_$policy -m mark --mark 0x0/0xff00 -m comment --comment "blackhole" -j MARK --set-xmark 0xfd00/0xff00
-		;;
-		default)
-			$IPT -A mwan3_policy_$policy -m mark --mark 0x0/0xff00 -m comment --comment "default" -j MARK --set-xmark 0xff00/0xff00
-		;;
-		*)
-			$IPT -A mwan3_policy_$policy -m mark --mark 0x0/0xff00 -m comment --comment "unreachable" -j MARK --set-xmark 0xfe00/0xff00
-		;;
-	esac
+	iptables -F mwan3_policy_$policy -t mangle
+	iptables -A mwan3_policy_$policy -t mangle -m mark --mark 0x0/0xff00 -m comment --comment "unreachable" -j MARK --set-xmark 0xfe00/0xff00
 
 	lowest_metric=256
 	total_weight=0
 
 	config_list_foreach $policy use_member mwan3_set_policy
+
+	iptables -X $policy -t mangle &> /dev/null
 }
 
 mwan3_set_user_rules_iptables()
@@ -266,18 +251,16 @@ mwan3_set_user_rules_iptables()
 			use_policy="MARK --set-xmark 0xff00/0xff00"
 		elif [ "$use_policy" == "unreachable" ]; then
 			use_policy="MARK --set-xmark 0xfe00/0xff00"
-		elif [ "$use_policy" == "blackhole" ]; then
-			use_policy="MARK --set-xmark 0xfd00/0xff00"
 		else
 			use_policy="mwan3_policy_$use_policy"
 		fi
 
 		case $proto in
 			tcp|udp)
-			$IPT -A mwan3_rules -p $proto -s $src_ip -d $dest_ip -m multiport --sports $src_port -m multiport --dports $dest_port -m mark --mark 0/0xff00 -m comment --comment "$1" -j $use_policy &> /dev/null
+			iptables -A mwan3_rules -t mangle -p $proto -s $src_ip -d $dest_ip -m multiport --sports $src_port -m multiport --dports $dest_port -m mark --mark 0/0xff00 -m comment --comment "$1" -j $use_policy &> /dev/null
 			;;
 			*)
-			$IPT -A mwan3_rules -p $proto -s $src_ip -d $dest_ip -m mark --mark 0/0xff00 -m comment --comment "$1" -j $use_policy &> /dev/null
+			iptables -A mwan3_rules -t mangle -p $proto -s $src_ip -d $dest_ip -m mark --mark 0/0xff00 -m comment --comment "$1" -j $use_policy &> /dev/null
 			;;
 		esac
 	fi
@@ -285,46 +268,51 @@ mwan3_set_user_rules_iptables()
 
 mwan3_ifupdown()
 {
-	local counter enabled iface_count iface_id route_args wan_metric
+	local count enabled iface_count iface_id route_args wan_metric
+
+	[ -n "$DEVICE" ] || exit 0
+	[ -n "$INTERFACE" ] || exit 0
+	[ "$(uci get -P /var/state mwan3.$INTERFACE 2> /dev/null)" == "interface" ] || return 0
 
 	config_load mwan3
-	config_foreach mwan3_get_iface_id interface
-
-	[ -n "$iface_id" ] || return 0
-	[ "$iface_count" -le 250 ] || return 0
-	unset iface_count
 
 	config_get enabled $INTERFACE enabled 0
 
-	counter=0
-
 	if [ $ACTION == "ifup" ]; then
-		[ "$enabled" -eq 1 ] || return 0
+		[ "$enabled" -eq 1 ] || exit 0
 
-		while [ -z "$($IP route list dev $DEVICE default | head -1)" -a "$counter" -lt 10 ]; do
+		count=0
+		while [ -z "$(ip -4 route list dev $DEVICE default | head -1)" -a "$count" -lt 10 ]; do
 			sleep 1
-			let counter++
-			if [ "$counter" -ge 10 ]; then
-				$LOG warn "Could not find gateway for interface $INTERFACE ($DEVICE)" && return 0
+			let count++
+			if [ "$count" -ge 10 ]; then
+				logger -t mwan3 -p warn "Could not find gateway for interface $INTERFACE ($DEVICE)" && exit 0
 			fi
 		done
+		unset count
 
-		route_args=$($IP route list dev $DEVICE default | head -1 | sed '/.*via \([^ ]*\) .*$/!d;s//via \1/;q' | egrep '[0-9]{1,3}(\.[0-9]{1,3}){3}')
-		route_args="nexthop $route_args dev $DEVICE"
+		mwan3_get_route_args
 	fi
 
-	while [ "$(pgrep -f -o hotplug-call)" -ne $$ -a "$counter" -lt 60 ]; do
+	count=0
+	while [ "$(pgrep -f -o hotplug-call)" -ne $$ -a "$count" -lt 60 ]; do
 		sleep 1
-		let counter++
-		if [ "$counter" -ge 60 ]; then
-			$LOG warn "Timeout waiting for older hotplug processes to finish. $ACTION interface $INTERFACE (${DEVICE:-unknown}) aborted" && return 0
+		let count++
+		if [ "$count" -ge 60 ]; then
+			logger -t mwan3 -p warn "Timeout waiting for older hotplug processes to finish. $ACTION interface $INTERFACE ($DEVICE) aborted" && exit 0
 		fi
 	done
+	unset count
 
-	$LOG notice "$ACTION interface $INTERFACE (${DEVICE:-unknown})"
+	config_foreach mwan3_get_iface_id interface
+
+	[ -n "$iface_id" ] || exit 0
+	[ "$iface_count" -le 250 ] || exit 0
+	unset iface_count
+
+	logger -t mwan3 -p notice "$ACTION interface $INTERFACE ($DEVICE)"
 
 	mwan3_set_general_iptables
-	mwan3_set_general_rules
 	mwan3_set_iface_iptables
 	mwan3_set_iface_route
 	mwan3_set_iface_rules
@@ -335,24 +323,9 @@ mwan3_ifupdown()
 	config_foreach mwan3_set_user_rules_iptables rule
 }
 
-[ -n "$ACTION" ] || exit 0
-[ -n "$INTERFACE" ] || exit 0
-
-if [ $ACTION == "ifup" ]; then
-	[ -n "$DEVICE" ] || exit 0
-fi
-
-local IP IPT LOG
-
-IP="/usr/sbin/ip -4"
-IPT="/usr/sbin/iptables -t mangle -w"
-LOG="/usr/bin/logger -t mwan3 -p"
-
 case "$ACTION" in
 	ifup|ifdown)
 		mwan3_ifupdown
 		mwan3_set_connected_iptables
 	;;
 esac
-
-exit 0
